--- Makefile	2011-11-28 09:14:58.000000000 -0500
+++ Makefile	2019-10-03 14:16:32.000000000 -0400
@@ -1,20 +1,18 @@
 ###################################################################
 
 all: 
-	cd Inchworm && ./configure --prefix=`pwd` && make install
-	cd Chrysalis && $(MAKE) UNSUPPORTED=yes
-	cd trinity-plugins/kmer && $(MAKE)
-	cd trinity-plugins/RSEM-mod && $(MAKE) 
-	cd trinity-plugins/bwa-0.5.7-patched_multi_map && $(MAKE)
+	cd Inchworm && ./configure --prefix=$(PREFIX) && make install
+	cd Chrysalis && $(MAKE) UNSUPPORTED=yes
+	cd trinity-plugins/kmer && $(MAKE)
+	cd trinity-plugins/RSEM-mod && $(MAKE) 
+	cd trinity-plugins/bwa-0.5.7-patched_multi_map && $(MAKE)
 
 clean:
-	cd Inchworm && make clean
-	cd Chrysalis && $(MAKE) clean UNSUPPORTED=yes
-	cd trinity-plugins/kmer && $(MAKE) clean
-	find trinity-plugins/kmer -name "*C.d" -exec rm -f {} \;
-	cd trinity-plugins/RSEM-mod && $(MAKE) clean
-	cd trinity-plugins/bwa-0.5.7-patched_multi_map && $(MAKE) clean
+	cd Inchworm && make clean
+	cd Chrysalis && $(MAKE) clean UNSUPPORTED=yes
+	cd trinity-plugins/kmer && $(MAKE) clean
+	find trinity-plugins/kmer -name "*C.d" -exec rm -f {} \;
+	cd trinity-plugins/RSEM-mod && $(MAKE) clean
+	cd trinity-plugins/bwa-0.5.7-patched_multi_map && $(MAKE) clean
 
 ###################################################################
-
-
